// packages/pulsix-react/src/PulsixButton.tsx
import React, { useRef, useEffect, useLayoutEffect, forwardRef, useImperativeHandle } from 'react';
import { createPulsixButton, PulsixButtonOptions, PulsixButtonInstance } from 'pulsix';

// Props per il componente React, eredita quelle della libreria core
export interface PulsixButtonProps extends Omit<PulsixButtonOptions, 'userId'> {
  // Rendi userId opzionale qui se vuoi, o passala sempre
  userId: string;
  // Aggiungi qui props specifiche React se necessario (es. className, style)
  className?: string;
  style?: React.CSSProperties;
}

// Definisci un handle per esporre metodi dell'istanza, se necessario
export interface PulsixButtonHandle {
  // Esempio: puoi esporre metodi specifici dell'istanza core se vuoi
  // getInstance: () => PulsixButtonInstance | null;
}

export const PulsixButton = forwardRef<PulsixButtonHandle, PulsixButtonProps>(
  ({ className, style, ...pulsixOptions }, ref) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const instanceRef = useRef<PulsixButtonInstance | null>(null);

    // Usa useLayoutEffect per manipolazioni DOM sincrone se necessario,
    // altrimenti useEffect va bene.
    useLayoutEffect(() => {
      let currentInstance: PulsixButtonInstance | null = null;
      if (containerRef.current) {
        // Pulisce il contenuto precedente se l'elemento viene riutilizzato
        while (containerRef.current.firstChild) {
           containerRef.current.removeChild(containerRef.current.firstChild);
        }
        // Crea l'istanza della libreria core
        currentInstance = createPulsixButton(containerRef.current, pulsixOptions);
        instanceRef.current = currentInstance;
      }

      // Funzione di cleanup
      return () => {
        currentInstance?.destroy();
        instanceRef.current = null;
      };
      // Ricrea l'istanza se le opzioni fondamentali cambiano (es. userId)
    }, [pulsixOptions.userId]); // Aggiungi qui altre dipendenze "fondamentali"

    // Effetto per aggiornare le opzioni non fondamentali
    useEffect(() => {
      if (instanceRef.current) {
        // Chiamiamo updateOptions solo per le opzioni che *possono* cambiare
        const { userId, ...updatableOptions } = pulsixOptions;
        instanceRef.current.updateOptions(updatableOptions);
      }
      // Aggiorna quando le opzioni (escluse quelle fondamentali) cambiano
    }, [pulsixOptions.label, pulsixOptions.onSuccess, pulsixOptions.onError /* ...altre opzioni */]);

    // Esponi metodi tramite ref se necessario (opzionale)
    useImperativeHandle(ref, () => ({
      // getInstance: () => instanceRef.current,
    }), []);

    // Renderizza un div contenitore che ospiterà il bottone creato dalla libreria
    return <div ref={containerRef} className={className} style={style}></div>;
  }
);

PulsixButton.displayName = 'PulsixButton'; // Utile per React DevTools

// packages/pulsix-solid/src/PulsixButton.tsx
import { onMount, onCleanup, createEffect, Component, splitProps } from 'solid-js';
import { createPulsixButton, PulsixButtonOptions, PulsixButtonInstance } from 'pulsix';
import type { JSX } from 'solid-js'; // Per tipi come HTMLAttributes

// Props per il componente Solid, eredita quelle della libreria core
// Usiamo Omit per escludere props che verranno gestite diversamente (es. ref)
export interface PulsixButtonProps extends Omit<PulsixButtonOptions, 'userId'> {
  userId: string;
  // Aggiungi qui props specifiche Solid/HTML se necessario
  class?: string;
  style?: JSX.CSSProperties | string;
}

export const PulsixButton: Component<PulsixButtonProps> = (props) => {
  let containerRef: HTMLDivElement | undefined;
  let instance: PulsixButtonInstance | null = null;

  // Separa le props della libreria core dalle props HTML standard (class, style, etc.)
  const [pulsixOptions, htmlProps] = splitProps(props, [
    "userId", "label", "onSuccess", "onError", /* ...altre PulsixButtonOptions */
  ]);

  onMount(() => {
    let currentInstance: PulsixButtonInstance | null = null;
    if (containerRef) {
      // Pulisci contenuto precedente
       while (containerRef.firstChild) {
          containerRef.removeChild(containerRef.firstChild);
       }
      // Crea l'istanza core
      currentInstance = createPulsixButton(containerRef, pulsixOptions);
      instance = currentInstance;
    }
    // La cleanup viene registrata qui per essere associata a questo onMount
    onCleanup(() => {
      currentInstance?.destroy();
      instance = null;
    });
  });

  // createEffect per aggiornare le opzioni quando le props cambiano
  // Solid traccia automaticamente le dipendenze (pulsixOptions)
  createEffect(() => {
    if (instance) {
      // Passiamo l'oggetto `pulsixOptions` direttamente,
      // Solid sa quando rieseguire l'effetto se cambiano
      const { userId, ...updatableOptions } = pulsixOptions;
      instance.updateOptions(updatableOptions);
    }
  });

  // Renderizza un div contenitore a cui la libreria si attaccherà
  // Applica le props HTML rimanenti (class, style, id, etc.)
  return <div ref={containerRef} {...htmlProps}></div>;
};
